### ISSUE TITLE
Offerings Recycle chance

### ISSUE THREAD

**Issue by pvahhi** [Pseudo-Corp/Synergism-Issue-Tracker#10]
In UI the message is:
"You have 70.5% chance of recycling your offerings. Recycled offerings are not spent!"

But actually 70% chance is applied when using offerings. 
Extra 0.5% is added only when displaying it. Probably should be removed from there.

**Comment by Pseudonian** [comment]
Thank you for noticing this. This will be fixed in v1.0084

**Comment by Pseudonian** [comment]
A fix was made for this in v1.0084.
