### ISSUE TITLE
Double dip on challenge six (Tax+) first completion

### ISSUE THREAD

**Issue by pvahhi** [Pseudo-Corp/Synergism-Issue-Tracker#11]
tax bonus  of 1.075 is applied twice.

First as (1 - 0.075 * Math.ceil(player.challengecompletions.six / 100))
And then again as f = 1/1.075

PS:Sorry Platonic I misled you on this. didn't realize first line is about first completion bonus :D

**Comment by Pseudonian** [comment]
This will be fixed in v1.0084.

**Comment by Pseudonian** [comment]
Created a fix for this
