### ISSUE TITLE
Importing save for a second time causes internal error

### ISSUE THREAD

**Issue by NyanCatTW1** [Pseudo-Corp/Synergism-Issue-Tracker#17]
**Describe the bug**
When I import the same exact savefile for a second time, it says the savefile is invalid, and after further investigating, I found out that the following error was thrown:
"TypeError: can't redefine non-configurable property "crystalUpgradesCost""
And the savefile was valid indeed because it worked the first time, which means a deeper issue is present. 
Version 1.0084

**To Reproduce**
Import any savefile twice in a row without refreshing.
To see the error, set browser debugger to pause on caught exceptions.

**Logs:**
Screenshot of the debugger on error caught:
![圖片](https://user-images.githubusercontent.com/17372086/82144719-e0e83300-9879-11ea-8e84-012db8f0ccde.png)

**Expected behavior**
The save imports successfully.

**Device:**
 - OS: Windows 10
 - OS Version: Version 1909, Build 18363.778
 - Browser: Firefox
 - Browser Version: 76.0.1 x64

**Additional Information:**
 - N/A

**Comment by KhafraDev** [comment]
issue fixed, patch will be included in a newer version
