### ISSUE TITLE
Improvement on obtainium offline gain late-game

### ISSUE THREAD

**Issue by NyanCatTW1** [Pseudo-Corp/Synergism-Issue-Tracker#7]
**What is your request about?**
 - [X] QoL Change
 - [ ] Feature Request

**Describe the game's current behavior:**
If you don't keep the game on overnight, you gain virtually no obtainium, which stops my progression heavily because I can only keep the game on for like 3 hours a day.

**Describe what should be added or changed:**
Either "simulate" the obtainium/offer gain in offline progress, or add research that provides offline obtainium production competable with online one, without buffing online production somehow.

**Comment by Pseudonian** [comment]
I think I can add this to v1.0084.

**Comment by Pseudonian** [comment]
This will be in the v1.0084 in the form of a new upgrade. Enjoy!
