### ISSUE TITLE
Rune sacriface buttons aren't displaying properly.

### ISSUE THREAD

**Issue by NyanCatTW1** [Pseudo-Corp/Synergism-Issue-Tracker#8]
**Describe the bug**
The edge of the sacriface buttons seem "cutted".

**To Reproduce**
1. Open the Runes tab.
2. Observe.

**Logs:**
[Nano] Nano Defender Activated :: game320578.konggames.com core.js:43:24
未宣告 HTML 文件的字元編碼。在某些設定的情況下若文件包含了 US-ASCII 以外的字元，將會顯示出亂碼。您必須在頁面或是傳輸通訊協定中宣告編碼。 live
SyntaxError: An invalid or illegal string was specified kongregate_api.js:36

**Expected behavior**
The buttons should display properly, without their edges cut.

**Device:**
 - OS: Windows 10
 - OS Version: Version 1909, Build 18363.778
 - Browser: Firefox
 - Browser Version: 76.0.1 x64

**Additional Information:**
That [Nano] thingy is my browser extension, should be ignorable.
Screenshots:
![圖片](https://user-images.githubusercontent.com/17372086/81802073-00b0eb80-9548-11ea-8327-7e5d0ebbfc12.png)
![圖片](https://user-images.githubusercontent.com/17372086/81802587-f3e0c780-9548-11ea-859e-79d4a5343231.png)

**Comment by Pseudonian** [comment]
tried my best to fix this, perhaps it works in update although this is an artifact of html bordering
