### ISSUE TITLE
Offline reincarnation does not give obtanium

### ISSUE THREAD

**Issue by blackreign** [Pseudo-Corp/Synergism-Issue-Tracker#9]
**Describe the bug**
Offline reincarnation does not give obtanium

**To Reproduce**
Set Reincarnation time to 3600
Close the game
Wait one hour
Open the game
Notice that you were reincarnated. you got the offerings, but no obtanium.

**Comment by Pseudonian** [comment]
This will be fixed in v1.0084.

**Comment by Pseudonian** [comment]
I hope this was fixed, it might not be but offline progress shold help mitigate the issue.
